"""Multi-ULog discrimination corpus (paper §8.8, v0.2.4 expansion).

The single-ULog discrimination experiment of v0.2.3 (paper §8.8)
proved that the verifier discriminates real telemetry against
buggy components on **one** PX4 SITL ULog. The single dataset was
the strongest residual reviewer objection: "does this generalise
across more flights?"

This module closes that gap by running the **full six-category
discrimination matrix** on a **corpus of structurally distinct
PX4 ULogs** (paper §8.8.1, v0.2.4):

- ``docs/paper/data/sample.ulg`` — PX4 v1.10 SITL flight,
  ~6.5 s, 636 pose samples (the original v0.2.3 dataset).
- ``docs/paper/data/corpus/sample_appended.ulg`` — multi-segment
  appended log, ~112 s, 1110 pose samples (longer-duration
  variation).
- ``docs/paper/data/corpus/sample_logging_tagged.ulg`` — tagged
  logging fixture with default params, ~10 s, 1268 pose samples
  (denser sampling rate).

All three are PX4 official test fixtures (PX4/pyulog), BSD-3
licensed. The corpus deliberately does not include cherry-picked
ULogs from individual flight reviews; we use the public,
auditable, license-clean set so a third party can reproduce the
matrix without us mediating access.

**Result reported in §8.8.1.** Each of the six buggy categories
(``calibrator_no_downgrade``, ``calibrator_invents_confidence``,
``decision_proceeds_anyway``, ``decision_never_proceeds``,
``actuation_non_safe_reason``, ``fpb_threshold_exceeded``) is
exercised on every ULog. The verifier flips the predicted property
**whenever the ULog exercises BAUD-v1's drift precondition** —
i.e. whenever the stationary belief diverges enough from the
recorded GT to fire. On 2/3 ULogs (``sample.ulg`` with FPB
``fire_fraction`` ≈ 0.94 and ``sample_appended.ulg`` ≈ 0.98), the
matrix is fully green: every category flips with full isolation
except ``calibrator_invents_confidence``, where BAUD also fires
because the inflated-confidence path is also stationary-belief
incompatible (a true co-violation, not a verifier artefact). On
``sample_logging_tagged.ulg`` (``fire_fraction`` ≈ 0.00 — the
recorded segment is largely stationary), 4/6 categories report
HOLDS across the board. This is **informative non-discrimination**:
the verifier correctly reports that the buggy producers were
never given an opportunity to exercise their precondition, not
that the bugs are undetectable. We report this honestly rather
than filtering the corpus to flights where every property fires.

The matrix is regenerated by ``run_multi_ulog_discrimination``
(or by CI on every push) and emitted to
``docs/paper/outputs/multi_ulog_discrimination/matrix.json`` for
third-party reproduction without re-running the SITL pipeline.

The discrimination experiment is purely synthetic ground-truth
(EKF2 self-consistent); ADR-0037 (independent ground truth) is
still open and is the next limitation we close (Fase 1.3),
which will also address the "all categories vacuously HOLD on
stationary ULogs" gap by sourcing drift from a non-self-consistent
reference.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import TYPE_CHECKING

from project_ghost.adapters.real_ulog_discrimination import (
    RealULogBugCategory,
    RealULogDiscriminationResults,
    run_real_ulog_discrimination,
)

if TYPE_CHECKING:
    from pathlib import Path


@dataclass(frozen=True)
class MultiULogCorpusResults:
    """Bundled output of the multi-ULog discrimination experiment.

    ``per_ulog`` maps each ULog filename to its single-ULog
    discrimination result. ``matrix`` is the boolean matrix
    indexed by ``[bug_category][ulog_name]`` recording whether
    that category discriminated on that ULog. The matrix flatness
    is invariant: if v0.2.4 ships a verifier that discriminates,
    then for every (category, ulog) pair the corresponding cell
    must be True.

    ``isolation_matrix``: like ``matrix`` but each cell records
    whether the bug *also* isolated — i.e. the violation was
    confined to the expected property and the other four held.
    A True in ``matrix`` and False in ``isolation_matrix`` means
    the verifier detected the bug but the violation spread; we
    flag this so the paper can be honest about which cells are
    "clean" isolated detections vs "noisy" detections.
    """

    per_ulog: dict[str, RealULogDiscriminationResults]
    matrix: dict[str, dict[str, bool]]
    isolation_matrix: dict[str, dict[str, bool]]

    @property
    def all_discriminate(self) -> bool:
        """True iff every cell of ``matrix`` is True."""
        return all(all(row.values()) for row in self.matrix.values())

    @property
    def all_isolated(self) -> bool:
        """True iff every detected cell also isolated."""
        return all(all(row.values()) for row in self.isolation_matrix.values())


def run_multi_ulog_discrimination(
    ulog_paths: list[Path],
    out_dir: Path,
    *,
    emit_json: bool = True,
) -> MultiULogCorpusResults:
    """Run the 6-category discrimination experiment on N ULogs.

    For each ULog, all six buggy categories are exercised; the
    resulting N-by-6 boolean matrix is the operational evidence that
    the discrimination property does not depend on the specific
    bundled fixture. Writes each per-ULog MCAP triple under
    ``out_dir/<ulog_stem>/`` and a reproducible JSON summary at
    ``out_dir/matrix.json``.

    Parameters
    ----------
    ulog_paths
        List of ``.ulg`` files. Must exist; each is parsed by the
        PX4 adapter. ULogs that do not produce pose samples raise
        ``ValueError``.
    out_dir
        Directory where per-ULog MCAPs are written. Created if it
        does not exist; existing files are overwritten.
    emit_json
        If True (default), emit ``out_dir/matrix.json`` containing
        the full detection + isolation matrices plus per-ULog
        diagnostics (cycles, ``fire_fraction``). Useful for paper
        reproducibility — a reader can inspect the matrix without
        re-running the SITL pipeline.

    Returns
    -------
    MultiULogCorpusResults
        ``all_discriminate`` is the single Boolean that pins the
        paper's expanded §8.8.1 claim. **Note**: this can be False
        legitimately (e.g. when a ULog is largely stationary and
        BAUD-v1's drift precondition never fires); the JSON output
        records ``fire_fraction`` per ULog so callers can
        distinguish "verifier missed the bug" from "ULog did not
        exercise the property's precondition".
    """
    if not ulog_paths:
        raise ValueError("ulog_paths is empty")

    out_dir.mkdir(parents=True, exist_ok=True)

    per_ulog: dict[str, RealULogDiscriminationResults] = {}
    for ulog in ulog_paths:
        stem = ulog.stem
        sub_out = out_dir / stem
        result = run_real_ulog_discrimination(ulog, sub_out)
        per_ulog[ulog.name] = result

    # Build the matrices. Outer key = bug category, inner key = ulog name.
    categories = [cat.value for cat in RealULogBugCategory]
    ulog_names = [p.name for p in ulog_paths]

    matrix: dict[str, dict[str, bool]] = {}
    isolation_matrix: dict[str, dict[str, bool]] = {}
    for cat_value in categories:
        matrix[cat_value] = {}
        isolation_matrix[cat_value] = {}
        for ulog_name in ulog_names:
            cells = [
                c for c in per_ulog[ulog_name].buggy_cells
                if c.category.value == cat_value
            ]
            if not cells:
                continue
            cell = cells[0]
            matrix[cat_value][ulog_name] = cell.discriminates
            isolation_matrix[cat_value][ulog_name] = (
                cell.discriminates and _is_isolated(cell)
            )

    results = MultiULogCorpusResults(
        per_ulog=per_ulog,
        matrix=matrix,
        isolation_matrix=isolation_matrix,
    )

    if emit_json:
        _emit_matrix_json(out_dir / "matrix.json", results, ulog_paths)

    return results


def _emit_matrix_json(
    json_path: Path,
    results: MultiULogCorpusResults,
    ulog_paths: list[Path],
) -> None:
    """Write a reproducible JSON summary of the corpus matrix.

    The JSON is the artefact paper readers and CI consume; it must
    be self-describing (no opaque field names) and must include
    per-ULog ``fire_fraction`` so a reader can tell whether a
    HOLDS row reflects a clean detection or a vacuously-held
    property on a stationary ULog.
    """
    diagnostics = {
        p.name: {
            "cycles_run": results.per_ulog[p.name].nominal.n_cycles_run,
            "fpb_fire_fraction": round(
                results.per_ulog[p.name].nominal.fpb_fire_fraction, 4
            ),
            "size_bytes": p.stat().st_size if p.exists() else None,
        }
        for p in ulog_paths
    }
    payload = {
        "schema_version": 1,
        "experiment": "multi_ulog_discrimination",
        "ulog_corpus": [p.name for p in ulog_paths],
        "diagnostics": diagnostics,
        "detection_matrix": results.matrix,
        "isolation_matrix": results.isolation_matrix,
        "all_discriminate": results.all_discriminate,
        "all_isolated": results.all_isolated,
    }
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True))


def _is_isolated(cell) -> bool:  # type: ignore[no-untyped-def]
    """Return True iff the bug violation is confined to the expected
    property; the other four properties must remain HOLD.

    Maps ``cell.expected_violator`` ("BAUD-v1" etc.) to the boolean
    field of ``cell.summary`` that should be False, and checks the
    other four are True.
    """
    s = cell.summary
    expected = cell.expected_violator
    fields = {
        "BAUD-v1": s.baud_holds,
        "ERUR-v1": s.erur_holds,
        "MD-v1": s.md_holds,
        "RLB-v1": s.rlb_holds,
        "FPB-v1": s.fpb_holds,
    }
    if fields[expected] is True:
        return False  # detection failed entirely
    # All other four must be True (held).
    return all(holds for prop, holds in fields.items() if prop != expected)


__all__ = [
    "MultiULogCorpusResults",
    "run_multi_ulog_discrimination",
]
